sudo: required

services:
  - docker

language: node_js

cache:
  yarn: true
  directories:
    - "node_modules"

node_js:
  - 8

script:
  - yarn test --coverage

after_script:
  - yarn coveralls

notifications:
  email: false
